#! /usr/bin/env sh
rm -r _build/prod/rel/acari_arm

export CROSSCOMPILE=1
export ERLANG_ARCH=32
export CC=/opt/nsgdevkit-2017-Q2/usr/bin/arm-nsg_rt-linux-gnueabi-gcc
export AR=/opt/nsgdevkit-2017-Q2/usr/bin/arm-nsg_rt-linux-gnueabi-ar
export RANLIB=/opt/nsgdevkit-2017-Q2/usr/bin/arm-nsg_rt-linux-gnueabi-ranlib
export ERTS_INCLUDE_DIR=/opt/erlang/arm_rt_eabi/erlang/erts-10.5.3/include
export ERL_INTERFACE_INCLUDE_DIR=/opt/erlang/arm_rt_eabi/erlang/lib/erl_interface-3.13/include
export ERL_INTERFACE_LIB_DIR=/opt/erlang/arm_rt_eabi/erlang/lib/erl_interface-3.13/lib
mix deps.clean procket
mix deps.update --all
MIX_ENV=prod mix release acari_arm
make -C deps/procket/c_src clean

cd _build/prod/rel/
tar -czf acari_arm.tar.gz acari_arm

#To Client
#scp acari_arm.tar.gz root@192.168.1.1:/tmp
#ssh root@192.168.1.1 "tar -C /usr/lib -mxzf /tmp/acari_arm.tar.gz"
