#! /usr/bin/env sh
rm -r _build/prod

make -C deps/procket/c_src clean
export CROSSCOMPILE=1
export ERLANG_ARCH=32
export CC=/opt/nsgdevkit-2017-Q2/usr/bin/arm-nsg_rt-linux-gnueabi-gcc
export AR=/opt/nsgdevkit-2017-Q2/usr/bin/arm-nsg_rt-linux-gnueabi-ar
export RANLIB=/opt/nsgdevkit-2017-Q2/usr/bin/arm-nsg_rt-linux-gnueabi-ranlib
export ERTS_INCLUDE_DIR=/home/igor/nsg/LoRa/erlang/erts-10.0.2/include
export ERL_INTERFACE_INCLUDE_DIR=/home/igor/nsg/LoRa/erlang/lib/erl_interface-3.10.3/include
export ERL_INTERFACE_LIB_DIR=/home/igor/nsg/LoRa/erlang/lib/erl_interface-3.10.3/lib
MIX_ENV=prod mix release --env=prod
cd _build/prod/rel/
rm acari/releases/0.1.0/acari.tar.gz
tar -czf acari.tar.gz acari
