#! /usr/bin/env sh
rm -r _build/prod

make -C deps/procket/c_src clean
export CROSSCOMPILE=1
export ERLANG_ARCH=32
export CC=/opt/nsgdevkit-2017-Q2/usr/bin/powerpc-nsg_rt-linux-gcc
export AR=/opt/nsgdevkit-2017-Q2/usr/bin/powerpc-nsg_rt-linux-ar
export RANLIB=/opt/nsgdevkit-2017-Q2/usr/bin/powerpc-nsg_rt-linux-ranlib
export ERTS_INCLUDE_DIR=/opt/erlang/powerpc_rt/erlang/erts-10.0.2/include
export ERL_INTERFACE_INCLUDE_DIR=/opt/erlang/powerpc_rt/erlang/lib/erl_interface-3.10.3/include
export ERL_INTERFACE_LIB_DIR=/opt/erlang/powerpc_rt/erlang/lib/erl_interface-3.10.3/lib
mix deps.get --only prod
MIX_ENV=prod mix release --env=prod
make -C deps/procket/c_src clean

cd _build/prod/rel/
rm acari_client/releases/0.1.0/acari_client.tar.gz
tar -czf acari_client.tar.gz acari_client

#To Client
scp acari_client.tar.gz root@192.168.1.1:/tmp
ssh root@192.168.1.1 "tar -C /usr/lib -mxzf /tmp/acari_client.tar.gz"
