#! /usr/bin/env sh
ERL="/opt/erlang/powerpc_rt/erlang-22.3.4"

rm -r _build/prod/rel/acari_powerpc

export CROSSCOMPILE=1
export ERLANG_ARCH=32
export CC=/opt/nsgdevkit-2017-Q2/usr/bin/powerpc-nsg_rt-linux-gcc
export AR=/opt/nsgdevkit-2017-Q2/usr/bin/powerpc-nsg_rt-linux-ar
export RANLIB=/opt/nsgdevkit-2017-Q2/usr/bin/powerpc-nsg_rt-linux-ranlib
export ERTS_INCLUDE_DIR=$ERL/erts-10.7.2/include
export ERL_INTERFACE_INCLUDE_DIR=$ERL/lib/erl_interface-3.13.2/include
export ERL_INTERFACE_LIB_DIR=$ERL/lib/erl_interface-3.13.2/lib
mix deps.clean procket
mix deps.update --all
MIX_ENV=prod mix release acari_powerpc
make -C deps/procket/c_src clean

cd _build/prod/rel/
tar -czf acari_powerpc.tar.gz acari_powerpc

#To Client
scp acari_powerpc.tar.gz root@192.168.1.1:/tmp
ssh root@192.168.1.1 "tar -C /usr/lib -mxzf /tmp/acari_powerpc.tar.gz"
