#! /usr/bin/env sh
ERL="/opt/erlang/aarch64_rt/erlang-24.3.4.13"
### ЕЩЕ подправить mix.exe !!!

rm -r _build/prod/rel/acari_arm64

export CROSSCOMPILE=1
export ERLANG_ARCH=64
export CC=/opt/nsgdevkit-2019-Q4/usr/bin/aarch64-nsg_rt-linux-gcc
export AR=/opt/nsgdevkit-2019-Q4/usr/bin/aarch64-nsg_rt-linux-ar
export RANLIB=/opt/nsgdevkit-2019-Q4/usr/bin/aarch64-nsg_rt-linux-ranlib
export ERTS_INCLUDE_DIR=$ERL/erts-12.3.2.13/include
export ERL_INTERFACE_INCLUDE_DIR=$ERL/lib/erl_interface-5.2.2/include
export ERL_INTERFACE_LIB_DIR=$ERL/lib/erl_interface-5.2.2/lib
mix deps.clean procket
mix deps.update --all
MIX_ENV=prod mix release acari_arm64
make -C deps/procket/c_src clean

cd _build/prod/rel/
tar -czf acari_arm64.tar.gz acari_arm64

#To Client
scp acari_arm64.tar.gz root@192.168.1.1:/tmp
ssh root@192.168.1.1 "tar -C /usr/lib -mxzf /tmp/acari_arm64.tar.gz"
